import {
  PROJECT_STAGE,
  PROJECT_STATUS,
  PROJECT_TASK,
  PROJECT_TYPE,
} from './enums';

export const PROJECT_TYPES = [
  PROJECT_TYPE.EXISTING_MACHINE,
  PROJECT_TYPE.RD_NEW_MACHINE,
  PROJECT_TYPE.OTHERS,
];

export const PROJECT_STATUSES = [
  PROJECT_STATUS.ACCEPTED,
  PROJECT_STATUS.COMPLETED,
  PROJECT_STATUS.IN_PROGRESS,
  PROJECT_STATUS.ON_HOLD,
];

export const PROJECT_STAGES = [
  PROJECT_STAGE.CREATING_PURCHASE_ORDER,
  PROJECT_STAGE.DELIVERY,
  PROJECT_STAGE.DESIGNING,
  PROJECT_STAGE.ESTIMATING_COST,
  PROJECT_STAGE.GENESIS,
  PROJECT_STAGE.IN_PRODUCTION,
];

export const PROJECT_TASKS = [
  PROJECT_TASK.ASSEMBLY,
  PROJECT_TASK.DESIGN,
  PROJECT_TASK.PURCHASES,
  PROJECT_TASK.TESTING,
];
